{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-coordinates
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ release }}.*
    - q2templates {{ release }}.*
    - q2-types {{ release }}.*
    - q2-diversity {{ release }}.*
    - pysal==2.1.0
    - cartopy==0.19
    - matplotlib==3.4.2
    - geopy==2.1.0
    - dill==0.3.4
    - geopandas==0.9.0
    - pandana==0.6.1
    - urbanaccess==0.2.2

test:
  imports:
    - q2_coordinates
    - qiime2.plugins.coordinates

about:
  home: https://github.com/bokulich-lab/q2-coordinates
  license: BSD-3-Clause
  license_family: BSD
